title: Alexander Pitkin (@peleccom)
email: pitkinalexander@gmail.com
description: >-
  Alexander Pitkin. Software engineer, 2026
baseurl: ""
url: "https://peleccom.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin: "default"

google_analytics: G-EPK3X1CQKB

search: true

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache

webmaster_verifications:
  yandex: 488b5d8930b870a1
  bing: 5E29942831C03280C5D417374C5438B9

author:
  name: "Alexander Pitkin"
  avatar: /me.png
  bio: "Software engineer with 12+ years of experience"
  location: "Minsk, Belarus"
  email: pitkinalexander@gmail.com
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:pitkinalexander@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/peleccom"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: "https://bitbucket.org/peleccom"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alexander-pitkin-9b21a457"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/peleccom"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/peleccom"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: "https://bitbucket.org/peleccom"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alexander-pitkin-9b21a457"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/peleccom"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "projects"
    values:
      layout: single
      author_profile: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-EPK3X1CQKB"
    anonymize_ip: false

atom_feed:
  hide: true
