services:
  jekyll:
    image: ruby:3.2
    command: bash -c "gem install bundler -v 2.4.22 --no-document && bundle install && bundle exec jekyll serve --watch --force_polling --verbose --host 0.0.0.0"
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll
    ports:
      - 4000:4000
